---

stages:
  - test

ansible-lint:
  image: python:3.10.4-bullseye
  stage: test
  script:
    - pip install --upgrade pip --quiet
    - pip install -r requirements.txt
    - yamllint .
    - ansible-lint
  interruptible: true
